name: date-util
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- time

library:
  source-dirs: src
  dependencies:
  - japanese-calendar
  ghc-options:
  - -Wall
  - -Werror
  - -O

executables:
  dateutil:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -O
    dependencies:
    - date-util

tests:
  date-util-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - hspec
    - date-util
